# This is a basic workflow to help you get started with Actions

name: DevTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'force-app/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'force-app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # commands using the runners shell
      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Populate auth file with SFDX_URL secret
        run: echo ${{ secrets.AUTH_CREATIVE }} > SFDX_AUTH_FILE

      - name: Authenticate
        run: sfdx force:auth:sfdxurl:store -f SFDX_AUTH_FILE -s
      
      - name: Instal delta sfdx plugin
        run: echo "y" | sfdx plugins:install sfdx-git-delta

      - name: Produce delta packages
        run: |
          sfdx sgd:source:delta --to HEAD --from HEAD^ --output .
          printf "\n--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          printf "\n--- destructiveChanges.xml generated with deleted metadata ---"
          cat destructiveChanges/destructiveChanges.xml

      - name: Run Test on Metadata
        run: sfdx force:source:deploy -x package/package.xml --testlevel=RunLocalTests --checkonly
